import {
  duration,
  easing,
  font,
  fontWeight,
  radius,
  space,
  typeScale,
  zIndex,
} from './primitives';
import { themes, type ThemeTokens } from './semantic';

const kebab = (s: string) =>
  s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/\./g, '_').toLowerCase();

/** Theme role names also split before digits: `surface2` → `surface-2`. */
const kebabRole = (s: string) => kebab(s).replace(/([a-z])(\d)/g, '$1-$2');

/** Flatten a semantic theme into `--color-*` / `--viz-*` / `--shadow-*` declarations. */
function themeVars(t: ThemeTokens): string[] {
  const out: string[] = [];
  const groups = ['bg', 'text', 'border', 'accent', 'status'] as const;
  for (const g of groups) {
    for (const [k, v] of Object.entries(t[g])) out.push(`--color-${g}-${kebabRole(k)}: ${v};`);
  }
  for (const [k, v] of Object.entries(t.viz)) {
    if (Array.isArray(v)) v.forEach((c, i) => out.push(`--viz-${kebab(k)}-${i + 1}: ${c};`));
    else out.push(`--viz-${kebab(k)}: ${v};`);
  }
  for (const [k, v] of Object.entries(t.shadow)) out.push(`--shadow-${k}: ${v};`);
  return out;
}

function staticVars(): string[] {
  const out: string[] = [];
  for (const [k, v] of Object.entries(space)) out.push(`--space-${String(k).replace('.', '_')}: ${v};`);
  for (const [k, v] of Object.entries(radius)) out.push(`--radius-${k}: ${v};`);
  out.push(`--font-sans: ${font.sans};`, `--font-mono: ${font.mono};`);
  for (const [k, v] of Object.entries(fontWeight)) out.push(`--font-weight-${k}: ${v};`);
  for (const [k, [size, lh, ls, w]] of Object.entries(typeScale)) {
    const n = kebab(k);
    out.push(
      `--text-${n}-size: ${size};`,
      `--text-${n}-line: ${lh};`,
      `--text-${n}-tracking: ${ls};`,
      `--text-${n}-weight: ${w};`,
    );
  }
  for (const [k, v] of Object.entries(duration)) out.push(`--duration-${k}: ${v};`);
  for (const [k, v] of Object.entries(easing)) out.push(`--ease-${k}: ${v};`);
  for (const [k, v] of Object.entries(zIndex)) out.push(`--z-${k}: ${v};`);
  return out;
}

const block = (selector: string, lines: string[]) =>
  `${selector} {\n${lines.map((l) => `  ${l}`).join('\n')}\n}\n`;

/** Full stylesheet: static scales + dark (default) + light theme. */
export function toCssVariables(): string {
  return [
    '/* AUTO-GENERATED by scripts/build-tokens.ts — do not edit by hand. */\n',
    block(':root', [...staticVars(), 'color-scheme: dark;', ...themeVars(themes.dark)]),
    block(':root[data-theme="light"]', ['color-scheme: light;', ...themeVars(themes.light)]),
  ].join('\n');
}
